# snapcraft.yaml - builds a Snap package of the Boot JDK
# Copyright (C) 2021 John Neffenger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: bootjdk
title: BootJDK
summary: Boot Java Development Kit
description: |
  This package contains the JDK used to build the JDK, called the Boot
  JDK. It provides OpenJDK versions 12, 13, and 14 on its candidate,
  beta, and edge channels. Its sole purpose is to bootstrap the
  build of OpenJDK 15 from trusted sources for the initial release
  of the OpenJDK Snap package. Note that OpenJDK versions 12, 13,
  and 14 are no longer maintained by Oracle or any other Java vendor.

  Do not install this package unless you have a historical interest in
  these old releases. Instead of this package, consider installing the
  currently maintained JDK release in the OpenJDK Snap package below:

  https://snapcraft.io/openjdk

  For more information, see the README file for this project on GitHub:

  https://github.com/jgneff/bootjdk

  Java and OpenJDK are trademarks or registered trademarks of Oracle
  and/or its affiliates.

# When the JDK release or build number changes, update the following:
#   version, slots, parts.jdk.build-environment.BUILD_NUM
version: '14.0.2+12'
license: (GPL-2.0 WITH Classpath-exception-2.0)

base: core18
grade: stable
confinement: strict

architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf
- build-on: i386
- build-on: ppc64el
- build-on: s390x

slots:
  jdk-14-1804:
    interface: content
    read: [$SNAP/jdk]

plugs:
  home: null

apps:
  bootjdk:
    command: bin/openjdk.sh
  java:
    command: jdk/bin/java
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - x11
    environment:
      LC_ALL: C.UTF-8
  javac:
    command: jdk/bin/javac
    environment:
      LC_ALL: C.UTF-8
  javadoc:
    command: jdk/bin/javadoc
    environment:
      LC_ALL: C.UTF-8
  jar:
    command: jdk/bin/jar
    environment:
      LC_ALL: C.UTF-8
  jarsigner:
    command: jdk/bin/jarsigner
    environment:
      LC_ALL: C.UTF-8
  jlink:
    command: jdk/bin/jlink
    environment:
      LC_ALL: C.UTF-8

parts:
  bin:
    plugin: dump
    source: .
    source-type: local
    stage: [bin]

  jdk:
    plugin: autotools
    source: https://github.com/openjdk/jdk14u.git
    source-branch: jdk-$SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    build-snaps:
    - bootjdk/latest/beta
    build-packages:
    - libasound2-dev
    - libcups2-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libx11-dev
    - libxext-dev
    - libxrandr-dev
    - libxrender-dev
    - libxt-dev
    - libxtst-dev
    - unzip
    - zip
    build-environment:
    - JAVA_HOME: /snap/bootjdk/current/jdk
    - BUILD_NUM: '12'
    # Option --disable-warnings-as-errors for armhf
    override-build: |
      set -o xtrace
      bash configure --enable-javac-server=no \
        --with-version-pre=no \
        --with-version-opt=snap \
        --with-version-build=$BUILD_NUM \
        --with-native-debug-symbols=none \
        --disable-warnings-as-errors
      make images docs
      cd build/linux-*-server-release/images
      mv jdk docs $SNAPCRAFT_PART_INSTALL
    organize:
      docs: jdk/docs
    stage-packages:
    - binutils
    - dpkg
    - fakeroot
    - libasound2
    - libfreetype6
    - libpng16-16
    - libx11-6
    - libxau6
    - libxcb1
    - libxdmcp6
    - libxext6
    - libxi6
    - libxrender1
    - libxtst6
    - libfontconfig1

  del:
    after: [jdk]
    plugin: nil
    # Deletes files and links already available in the base snap
    override-prime: |
      set -o xtrace
      cd $SNAPCRAFT_PRIME
      base=/snap/core18/current
      find * -type f -exec test -f "$base/{}" \; -delete
      find * -type l -exec test -L "$base/{}" \; -delete
      find * -type d -empty -exec test -d "$base/{}" \; -delete

layout:
  # Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
  /etc/fonts:
    bind: $SNAP/etc/fonts
